### ISSUE TITLE
pip version doesn't import

### ISSUE THREAD

**Issue by dave31415** [cvxgrp/ncvx#1]
/Users/davej/anaconda2/anaconda/lib/python2.7/site-packages/ncvx/**init**.py in <module>()
     29 from .rank import Rank
     30 from .sphere import Sphere
---> 31 from .soc_boundary import SOCBound
     32 from .tour import Tour

ImportError: No module named soc_boundary

I can install and import from github version. Might want to update pip.

**Comment by SteveDiamond** [comment]
Fixed.
