### ISSUE TITLE
TypeError: ABCMeta object argument after * must be an iterable, not numpy.int32

### ISSUE THREAD

**Issue by jamesdvance** [cvxgrp/ncvx#10]
Recently re-installed ncvx, numpy and cvxopt. Code is throwing the error in the subject when I run the code below (have updated with the new Choose parameters:
`x = Choose(rows=len(df),cols=1,k=k)`
Any help greatly appreciated

**Comment by jamesdvance** [comment]
Full error:

`~\Desktop\Git_Repositories\meal_maker\plan_maker_alg\optimization\nonconvex_opt_functions.py in solve_nc_admm(df, reqs_df, k, mac_cols, nut_cols)
     23                 req_mat = np.hstack([req_mat, new_col[0,None][:,None]])
     24 
---> 25     x = Choose(rows=int(len(df)),cols=1,k=k)
     26     objective = cvx.sum_squares(x.T*pln_mat-req_mat)
     27     prob = cvx.Problem(cvx.Minimize(objective))

C:\Anaconda3\lib\site-packages\ncvx\choose.py in __init__(self, rows, cols, k, *args, **kwargs)
     27             raise Exception("Choose requires a value for k.")
     28         self.k = k
---> 29         super(Choose, self).__init__(rows, cols, *args, **kwargs)
     30 
     31     def init_z(self, random):

C:\Anaconda3\lib\site-packages\ncvx\noncvx_variable.py in __init__(self, *args, **kwargs)
     27         super(NonCvxVariable, self).__init__(*args, **kwargs)
     28         self.noncvx = True
---> 29         self.z = cvxpy.Parameter(*self.size)
     30         self.u = cvxpy.Parameter(*self.size)
     31         self.u.value = np.zeros(self.size)

TypeError: ABCMeta object argument after * must be an iterable, not numpy.int32`

**Comment by SteveDiamond** [comment]
ncvx only works with cvxpy 0.4.

**Comment by jamesdvance** [comment]
That fixed it (and still in Py 3.6) Greatly appreciate it.
