### ISSUE TITLE
The examples do not run properly

### ISSUE THREAD

**Issue by HangTian2020** [cvxgrp/ncvx#16]
I installed python 3.5, cvxpy 0.4, scsprox and ncvx 0.1.8 as the README said, but all the examples show errors.
Also, the NCVX supported functions do not work well, such as ``integer(n, M)``.
Is there anything wrong with the versions of installed modules?
Thanks for your time.

**Comment by SteveDiamond** [comment]
Try reinstalling. The version on pip was out of date.

**Comment by HangTian2020** [comment]
Thanks for your updating.
I reinstalled ncvx-0.1.9 and ran the example in README.
It still got an error:

Traceback (most recent call last):
  File "C:\Users\th233\Desktop\ncvx-0.1.9\ncvx-0.1.9\readme example.py", line 20, in <module>
    x = Card(n, k, 1)
  File "C:\Users\th233\Desktop\ncvx-0.1.9\ncvx-0.1.9\ncvx\card.py", line 33, in __init__
    super(Card, self).__init__(rows, 1, *args, **kwargs)
  File "C:\Users\th233\Desktop\ncvx-0.1.9\ncvx-0.1.9\ncvx\noncvx_variable.py", line 31, in __init__
    self.z = cvxpy.Parameter(self.shape)
AttributeError: 'Card' object has no attribute 'shape'

It seems that "Card" supported by NCVX does not work.

**Comment by bettbra** [comment]
I think you can close this now @SteveDiamond. Examples are all back to operational with that latest merge.
