### ISSUE TITLE
None of the examples in ncvx/examples that use NC-ADMM run properly

### ISSUE THREAD

**Issue by Shuvomoy** [cvxgrp/ncvx#9]
For a personal research project I am trying to reproduce the numerical experiments that use NC-ADMM in the paper: 

"A General System for Heuristic Solution of Convex Problems over Nonconvex Sets by S. Diamond, R. Takapoui, and S. Boyd"

and compare the performance with nonconvex Douglas-Rachford splitting. 

But none of the examples in ncvx/examples that use NC-ADMM run properly. I followed the instructions exactly as told in Readme, but each of the NC-ADMM examples throws errors. I have Python 2.7, latest Anaconda, CVXPY and NCVX. Any help will be appreciated.

**Comment by SteveDiamond** [comment]
Are you using cvxpy 1.0? ncvx is not yet upgraded to handle cvxpy 1.0. You must use cvxpy 0.4.

**Comment by Shuvomoy** [comment]
Thanks for the info. I could make all the examples (except the traveling salesman problem) work by manually installing cvxpy 0.4.11, ncvx commit 3bf53ca (the newest commit for python 3 does not work) and scsprox. For me that suffices so I am closing the issue.
